name: Fetch Folder and Push to Current Repo

on:
  workflow_dispatch:  # Manually triggered

jobs:
  fetch-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v4

    - name: Configure Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Clone specific folder from another repository
      run: |
        git clone --depth 1 --filter=blob:none --sparse https://${{TOKEN_GITHUB}}@github.com/supertypeai/sectors_idx_highlights temp-repo
        cd temp-repo
        git sparse-checkout set json_output
        cd ..

    - name: Copy files to current repository
      run: |
        mkdir -p json_output  # Change if needed
        cp -R temp-repo/path/to/folder/* json_output/

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Automated: Sync folder from external repository" || echo "Nothing to commit"
        git push
